# Generated by Django 3.0.8 on 2020-08-03 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liftblog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='textpost',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
