# Generated by Django 3.0.8 on 2020-08-05 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liftblog', '0002_textpost_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='videopost',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
