# Generated by Django 3.0.8 on 2020-08-22 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liftblog', '0005_auto_20200822_2341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videopost',
            name='post_video',
            field=models.FileField(blank=True, upload_to='videos/'),
        ),
    ]
